# Generated by Django 5.2.7 on 2025-11-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tag_created_at_tag_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
    ]
